In [2]:
import numpy as np

my_array = np.array([[1, 2,3], [4, 5, 6], [7, 8, 9]])

In [3]:
import pandas as pd

my_dataset = pd.DataFrame(my_array)

In [4]:
print(my_dataset)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [5]:
my_dataset

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
index = [ 'A', 'B', 'C']
columns = ['D', 'E', 'F']

df = pd.DataFrame(data = my_array, index=index, columns=columns)

In [7]:
df

   D  E  F
A  1  2  3
B  4  5  6
C  7  8  9

### Exploring the data frame

In [8]:
df.head(2)

   D  E  F
A  1  2  3
B  4  5  6

In [9]:
df.tail(2)

   D  E  F
B  4  5  6
C  7  8  9

In [10]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, A to C
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   D       3 non-null      int64
 1   E       3 non-null      int64
 2   F       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [13]:
# Dimension of the data frame
df.shape

(3, 3)

In [14]:
df.describe()

         D    E    F
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [15]:
df.columns

Index(['D', 'E', 'F'], dtype='str')

In [16]:
df.index

Index(['A', 'B', 'C'], dtype='str')

In [17]:
# Add a new row to the data frame
df.loc['G'] = [10, 11, 12]

In [18]:
df

    D   E   F
A   1   2   3
B   4   5   6
C   7   8   9
G  10  11  12

In [19]:
df['H'] = [17, 16, 15, 14]

In [20]:
df

    D   E   F   H
A   1   2   3  17
B   4   5   6  16
C   7   8   9  15
G  10  11  12  14

In [21]:
# Extracting columns
df_2 = df[['D', 'E']]

In [22]:
df_2

    D   E
A   1   2
B   4   5
C   7   8
G  10  11

In [23]:
df_3 = df.iloc[0:2]

In [24]:
df_3

   D  E  F   H
A  1  2  3  17
B  4  5  6  16

In [25]:
df.columns = ['Col 1', 'Col 2', 'Col 3', 'Col 4']
df

   Col 1  Col 2  Col 3  Col 4
A      1      2      3     17
B      4      5      6     16
C      7      8      9     15
G     10     11     12     14

In [28]:
df.rename(index = {'A': 'data 1', 'B': 'data 2'}, inplace = True)
df

        Col 1  Col 2  Col 3  Col 4
data 1      1      2      3     17
data 2      4      5      6     16
C           7      8      9     15
G          10     11     12     14

In [30]:
# Sorting the data respect a column
df_4 = df.sort_values('Col 4', ascending = True)
df_4

        Col 1  Col 2  Col 3  Col 4
G          10     11     12     14
C           7      8      9     15
data 2      4      5      6     16
data 1      1      2      3     17

In [31]:
#Verify conditions int the data frame
df['Col 2'] > 5

data 1    False
data 2    False
C          True
G          True
Name: Col 2, dtype: bool

In [33]:
df[df['Col 2'] > 5]

   Col 1  Col 2  Col 3  Col 4
C      7      8      9     15
G     10     11     12     14

In [35]:
condition_1 = df['Col 2'] > 5
condition_2 = df['Col 2'] < 11
df[condition_1 & condition_2]

   Col 1  Col 2  Col 3  Col 4
C      7      8      9     15

In [36]:
pd.__version__

'3.0.5'

In [37]:
# EDA with descriptive statistical
my_data_3 = {
"Producto": ["Manzanas", "Bananas", "Naranjas", "Uvas", "Peras"],
"Cantidad": [10, 20, 15, 12, 8],
"Precio": [5.5, 2.5, 3.0, 4.5, 6.0],
"Categoria": ["Frutas", "Frutas", "Frutas", "Frutas", "Frutas"]}

In [38]:
my_dp= pd.DataFrame(my_data_3)

In [40]:
print('Dataframe EDA')
print(my_dp.describe())

Dataframe EDA
        Cantidad    Precio
count   5.000000  5.000000
mean   13.000000  4.300000
std     4.690416  1.524795
min     8.000000  2.500000
25%    10.000000  3.000000
50%    12.000000  4.500000
75%    15.000000  5.500000
max    20.000000  6.000000

In [42]:
mean_quantity = my_dp['Cantidad'].mean()
sum_quantity = my_dp['Cantidad'].sum()

print(f'Mean quantity: {mean_quantity}')
print(f'Sum quantity: {sum_quantity}')

Mean quantity: 13.0
Sum quantity: 65

### Filtering multiple conditions

In [47]:
# Filter products with a quantity great than 10 and less than 5
filter_1 = my_dp['Cantidad'] > 10
filter_2 = my_dp['Precio'] < 5

condition_3 = my_dp[filter_1 & filter_2]
print('Products with price less than 5 and quantity great than 10')
print(condition_3)

Products with price less than 5 and quantity great than 10
   Producto  Cantidad  Precio Categoria
1   Bananas        20     2.5    Frutas
2  Naranjas        15     3.0    Frutas
3      Uvas        12     4.5    Frutas

### Pivot table for data analisys

In [64]:
datos_ext = {
"Producto": ["Manzanas", "Bananas", "Naranjas", "Uvas", "Manzanas", "Bananas"],
"Cantidad": [10, 20, 15, 12, 5, 10],
"Precio": [5.5, 2.5, 3.0, 4.5, 5.5, 2.5],
"Mes": ["Enero", "Enero", "Enero", "Enero", "Febrero", "Febrero"]
}

my_dp_ext = pd.DataFrame(datos_ext)

In [49]:
# Create a pivot table
pivot_table = my_dp_ext.pivot_table(values= 'Cantidad', index= 'Producto', columns='Precio', aggfunc= 'sum', fill_value=0)
print('Dynamic table of quantities by month')
print(pivot_table)

Dynamic table of quantities by month
Precio    2.5  3.0  4.5  5.5
Producto
Bananas    30    0    0    0
Manzanas    0    0    0   15
Naranjas    0   15    0    0
Uvas        0    0   12    0

In [51]:
my_dp_ext.describe()
print(my_dp_ext)

   Producto  Cantidad  Precio      Mes
0  Manzanas        10     5.5    Enero
1   Bananas        20     2.5    Enero
2  Naranjas        15     3.0    Enero
3      Uvas        12     4.5    Enero
4  Manzanas         5     5.5  Febrero
5   Bananas        10     2.5  Febrero

### Custom functions

In [52]:
# Classify with price
def classify_by_price(price):
    if price < 3:
        return 'Cheap'
    elif price < 5:
        return 'Reasonable'
    else:
        return 'Expensive'

In [53]:
# Apply a new colum this new classification
my_dp_ext['Price classification'] = my_dp_ext['Precio'].apply(classify_by_price)
print('Data table with price classification')
print(my_dp_ext)

Data table with price classification
   Producto  Cantidad  Precio      Mes Price classification
0  Manzanas        10     5.5    Enero            Expensive
1   Bananas        20     2.5    Enero                Cheap
2  Naranjas        15     3.0    Enero           Reasonable
3      Uvas        12     4.5    Enero           Reasonable
4  Manzanas         5     5.5  Febrero            Expensive
5   Bananas        10     2.5  Febrero                Cheap

### Operations with duplicated data

In [57]:
new_row = pd.DataFrame({"Producto": ["Manzanas"], "Cantidad": [10], "Precio": [5.5], "Categoria": ["Frutas"], "Price classification": [classify_by_price(5.5)]})

my_data_ext = pd.concat([new_row, my_dp_ext], ignore_index=True)
print(my_data_ext)

   Producto  Cantidad  Precio Categoria Price classification      Mes
0  Manzanas        10     5.5    Frutas            Expensive      NaN
1  Manzanas        10     5.5       NaN            Expensive    Enero
2   Bananas        20     2.5       NaN                Cheap    Enero
3  Naranjas        15     3.0       NaN           Reasonable    Enero
4      Uvas        12     4.5       NaN           Reasonable    Enero
5  Manzanas         5     5.5       NaN            Expensive  Febrero
6   Bananas        10     2.5       NaN                Cheap  Febrero

In [59]:
duplicated_df = my_dp_ext.duplicated(subset=["Producto", "Cantidad", "Precio"], keep=False)

print(duplicaed_df)

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

In [61]:
without_duplicated = my_dp_ext.drop_duplicates()
print(without_duplicated)

   Producto  Cantidad  Precio      Mes Price classification
0  Manzanas        10     5.5    Enero            Expensive
1   Bananas        20     2.5    Enero                Cheap
2  Naranjas        15     3.0    Enero           Reasonable
3      Uvas        12     4.5    Enero           Reasonable
4  Manzanas         5     5.5  Febrero            Expensive
5   Bananas        10     2.5  Febrero                Cheap

In [66]:
print(my_dp_ext)

   Producto  Cantidad  Precio      Mes
0  Manzanas        10     5.5    Enero
1   Bananas        20     2.5    Enero
2  Naranjas        15     3.0    Enero
3      Uvas        12     4.5    Enero
4  Manzanas         5     5.5  Febrero
5   Bananas        10     2.5  Febrero

In [65]:
# Group data by category and make multiple operations
grop_by_category = my_dp_ext.groupby("Categoria").agg({"Cantidad": ["sum", "mean"], "Precio": ["mean"]})

KeyError: 'Categoria'

In [2]:
import pandas as pd
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [5]:
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]), 'frame': None, 'target_names': array(['setosa', 'versicolor', 'virginica'], dtype='<U10'), 'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 33.3% for each of 3 classes.\n:Creator: R.A. Fisher\n:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)\n:Date: July, 1988\n\nThe famous Iris database, first used by Sir R.A. Fisher. The dataset is taken\nfrom Fisher\'s paper. Note that it\'s the same as in R, but not as in the UCI\nMachine Learning Repository, which has two wrong data points.\n\nThis is perhaps the best known database to be found in the\npattern recognition literature.  Fisher\'s paper is a classic in the field and\nis referenced frequently to this day.  (See Duda & Hart, for example.)  The\ndata set contains 3 classes of 50 instances each, where each class refers to a\ntype of iris plant.  One class is linearly separable from the other 2; the\nlatter are NOT linearly separable from each other.\n\n.. dropdown:: References\n\n  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"\n    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to\n    Mathematical Statistics" (John Wiley, NY, 1950).\n  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.\n    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.\n  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System\n    Structure and Classification Rule for Recognition in Partially Exposed\n    Environments".  IEEE Transactions on Pattern Analysis and Machine\n    Intelligence, Vol. PAMI-2, No. 1, 67-71.\n  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions\n    on Information Theory, May 1972, 431-433.\n  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II\n    conceptual clustering system finds 3 classes in the data.\n  - Many, many more ...\n', 'feature_names': ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'], 'filename': 'iris.csv', 'data_module': 'sklearn.datasets.data'}

In [6]:
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [9]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [10]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [12]:
df_filtered = df[(df['sepal width (cm)'] >= 3.5) & (df['sepal length (cm)'] >= 5.0)]
df_filtered

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
4                  5.0               3.6                1.4               0.2
5                  5.4               3.9                1.7               0.4
10                 5.4               3.7                1.5               0.2
14                 5.8               4.0                1.2               0.2
15                 5.7               4.4                1.5               0.4
16                 5.4               3.9                1.3               0.4
17                 5.1               3.5                1.4               0.3
18                 5.7               3.8                1.7               0.3
19                 5.1               3.8                1.5               0.3
21                 5.1               3.7                1.5               0.4
27                 5.2               3.5                1.5               0.2
32                 5.2               4.1                1.5               0.1
33                 5.5               4.2                1.4               0.2
36                 5.5               3.5                1.3               0.2
40                 5.0               3.5                1.3               0.3
43                 5.0               3.5                1.6               0.6
44                 5.1               3.8                1.9               0.4
46                 5.1               3.8                1.6               0.2
48                 5.3               3.7                1.5               0.2
109                7.2               3.6                6.1               2.5
117                7.7               3.8                6.7               2.2
131                7.9               3.8                6.4               2.0

In [15]:
total_registers = df_filtered.shape
print(total_registers[0])

23

In [16]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='str')

In [ ]:
aggregated = df_filtered.groupby('')