# Python Decision Tree

In [1]:
# load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import matplotlib.pyplot as plt

## Sample 1. Fraud

In [2]:
# load fraud dataset
fraud_data = pd.read_csv('Fraude.csv')
fraud_data.sample(5)

   ID Reembolso EdoCivil  Ingresos Fraude
7   8        No  Soltero     85000     Sí
1   2        No   Casado    100000     No
9  10        No  Soltero     90000     Sí
3   4        Sí   Casado    120000     No
8   9        No   Casado     75000     No

In [3]:
# Set the columns to be used as features matrix X and target variable Y
feature_columns = ['Reembolso', 'EdoCivil', 'Ingresos']
X = fraud_data[feature_columns].values
Y = fraud_data.Fraude

In [4]:
# Preprocessing to generate numerical values from categorical values
from sklearn import preprocessing

refound_codfication = preprocessing.LabelEncoder()
refound_codfication.fit(['No', 'Sí'])
X[:, 0] = refound_codfication.transform(X[:, 0])

marital_status_codfication = preprocessing.LabelEncoder()
marital_status_codfication.fit(['Casado', 'Divorciado', 'Soltero'])
X[:, 1] = marital_status_codfication.transform(X[:, 1])

In [5]:
X[0:5]

array([[1, 2, 125000],
       [0, 0, 100000],
       [0, 2, 70000],
       [1, 0, 120000],
       [0, 1, 95000]], dtype=object)

In [6]:
# Build training and testing sets
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=1)

In [7]:
# Build the decision tree classifier model
clf = DecisionTreeClassifier()

# Apply the model to the training data
clf = clf.fit(X_train, Y_train)

# Predict the response for the test dataset
y_hat = clf.predict(X_test)

In [8]:
X_test

array([[0, 2, 70000],
       [0, 2, 90000],
       [1, 1, 220000]], dtype=object)

In [9]:
y_hat

array(['Sí', 'Sí', 'No'], dtype=object)

In [10]:
Y_test

2    No
9    Sí
6    No
Name: Fraude, dtype: str

In [11]:
# Confusion matrix
confusion_matrix = metrics.confusion_matrix(Y_test, y_hat)
confusion_matrix

array([[1, 1],
       [0, 1]])

In [12]:
# Show the report of the model
print(metrics.classification_report(Y_test, y_hat))

              precision    recall  f1-score   support

          No       1.00      0.50      0.67         2
          Sí       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

In [37]:
# load more libraries 
from sklearn import tree
import graphviz
import pydotplus
from PIL import Image

In [39]:
# Set the decision rules to be used in the decision tree
dot_data = tree.export_graphviz(clf, out_file=None, 
                                feature_names=feature_columns,  
                                class_names=['No', 'Sí'])

# Build the decision tree graph
graph = pydotplus.graph_from_dot_data(dot_data)

In [40]:
# Export the decision tree graph to a PDF file
graph.write_pdf("DecisionTree.pdf")

# Export the decision tree graph to a PNG file
graph.write_png("DecisionTree.png")

image = Image.open("DecisionTree.png")
image .show()

# Sample 2. Diabetes

In [41]:
# Loada dataset to be used in the decision tree, in this case, the diabetes dataset
diabetes_data_frame = pd.read_csv('diabetes.csv')
diabetes_data_frame.sample(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
718,1,108,60,46,178,35.5,0.415,24,0
660,10,162,84,0,0,27.7,0.182,54,0
612,7,168,88,42,321,38.2,0.787,40,1
749,6,162,62,0,0,24.3,0.178,50,1
129,0,105,84,0,0,27.9,0.741,62,1

In [42]:
# Selection of the features and target variable for the diabetes dataset
feature_columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
X = diabetes_data_frame[feature_columns]
Y = diabetes_data_frame.Outcome

In [43]:
X

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,0,33.6,0.627,50
1,1,85,66,0,26.6,0.351,31
2,8,183,64,0,23.3,0.672,32
3,1,89,66,94,28.1,0.167,21
4,0,137,40,168,43.1,2.288,33
...,...,...,...,...,...,...,...
763,10,101,76,180,32.9,0.171,63
764,2,122,70,0,36.8,0.340,27
765,5,121,72,112,26.2,0.245,30
766,1,126,60,0,30.1,0.349,47
767,1,93,70,0,30.4,0.315,23

In [44]:
Y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [45]:
# Set the training and testing sets for the diabetes dataset
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1) # As the dataset is bigger than the fraud one, we will use 20% of the data for testing

In [47]:
# Build the decision tree classifier model
clf = DecisionTreeClassifier(criterion='gini')

# Apply the model to the training data
clf = clf.fit(X_train, Y_train)

# Predict the response for the test dataset
y_hat = clf.predict(X_test)

In [48]:
# Confusion matrix
confusion_matrix = metrics.confusion_matrix(Y_test, y_hat)
confusion_matrix

array([[78, 21],
       [24, 31]])

In [49]:
# Show the report of the model
print(metrics.classification_report(Y_test, y_hat))

              precision    recall  f1-score   support

           0       0.76      0.79      0.78        99
           1       0.60      0.56      0.58        55

    accuracy                           0.71       154
   macro avg       0.68      0.68      0.68       154
weighted avg       0.70      0.71      0.71       154

In [50]:
# Set the decision rules to be used in the decision tree
dot_data = tree.export_graphviz(clf, out_file=None, 
                                feature_names=feature_columns,  
                                class_names=['Normal', 'Diabetes'])

# Build the decision tree graph
graph = pydotplus.graph_from_dot_data(dot_data)

In [51]:
# Export the decision tree graph to a PDF file
graph.write_pdf("Diabetes.pdf")

# Export the decision tree graph to a PNG file
graph.write_png("Diabetes.png")

image = Image.open("Diabetes.png")
image .show()

## Optimization with entropy

In [52]:
# Build the decision tree classifier model
clf = DecisionTreeClassifier(criterion='entropy', max_depth=3)

# Apply the model to the training data
clf = clf.fit(X_train, Y_train)

# Predict the response for the test dataset
y_hat = clf.predict(X_test)

In [53]:
# Show the report of the model
print(metrics.classification_report(Y_test, y_hat))

              precision    recall  f1-score   support

           0       0.81      0.89      0.85        99
           1       0.76      0.64      0.69        55

    accuracy                           0.80       154
   macro avg       0.79      0.76      0.77       154
weighted avg       0.80      0.80      0.79       154

In [54]:
# Set the decision rules to be used in the decision tree
dot_data = tree.export_graphviz(clf, out_file=None, 
                                feature_names=feature_columns,  
                                class_names=['Normal', 'Diabetes'])

# Build the decision tree graph
graph = pydotplus.graph_from_dot_data(dot_data)

In [55]:


# Export the decision tree graph to a PDF file
graph.write_pdf("Diabetes_entropy.pdf")

# Export the decision tree graph to a PNG file
graph.write_png("Diabetes_entropy.png")

image = Image.open("Diabetes_entropy.png")
image .show()

In [56]:
# Formating the decision tree graph to be shown in the notebook
from six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz

In [63]:
import pydot 
dot_data = StringIO()
export_graphviz(clf, out_file=dot_data, filled=True, rounded=True,
                special_characters=True, feature_names = feature_columns, class_names=['Normal', 'Diabetes'])
graph = pydot.graph_from_dot_data(dot_data.getvalue())[0]

In [66]:
from PIL import Image
graph.write_png("Diabetes_entropy_formated.png")
graph.write_pdf("Diabetes_entropy_formated.pdf")
image = Image.open("Diabetes_entropy_formated.png")
image .show()